"""add Indexing to exercise

Revision ID: 26aeeec5b2d1
Revises: 5b689e523c3f
Create Date: 2026-04-13 13:28:17.898974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26aeeec5b2d1'
down_revision: Union[str, Sequence[str], None] = '5b689e523c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_exercises_created_by', 'exercises', ['created_by'], unique=False)
    op.create_index('ix_exercises_equipment', 'exercises', ['equipment'], unique=False)
    op.create_index('ix_exercises_is_custom', 'exercises', ['is_custom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercises_is_custom', table_name='exercises')
    op.drop_index('ix_exercises_equipment', table_name='exercises')
    op.drop_index('ix_exercises_created_by', table_name='exercises')
    # ### end Alembic commands ###
