"""add age and height_cm to user_body_metrics

Revision ID: 5b689e523c3f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 12:56:10.946829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b689e523c3f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_body_metrics', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_body_metrics', sa.Column('height_cm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_body_metrics', 'height_cm')
    op.drop_column('user_body_metrics', 'age')
    # ### end Alembic commands ###
