"""
Rex agent tools.

get_data       — executes a SELECT query generated by the agent.
create_routine — saves a new routine using structured parameters (tool builds the SQL).
"""
import os
import re

from dotenv import load_dotenv
from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine


load_dotenv()

_db_url = os.environ["DATABASE_URL"].replace("postgresql://", "postgresql+asyncpg://", 1)
_engine = create_async_engine(_db_url, pool_pre_ping=True)
_SessionFactory = async_sessionmaker(bind=_engine, expire_on_commit=False)

# ── Read-only guard ────────────────────────────────────────────────────────────

# Any keyword that writes, modifies, or executes — block regardless of position.
_WRITE_KEYWORDS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|MERGE|REPLACE"
    r"|EXECUTE|EXEC|CALL|GRANT|REVOKE|COPY)\b",
    re.IGNORECASE,
)

# SELECT INTO creates a new table — not a data read.
_SELECT_INTO = re.compile(r"\bSELECT\b.+\bINTO\b", re.IGNORECASE | re.DOTALL)


def _assert_read_only(query: str) -> None:
    """Raise ValueError if the query is not a plain read-only SELECT."""
    # Strip SQL comments so they cannot be used to hide keywords.
    clean = re.sub(r"--[^\n]*", "", query)           # single-line comments
    clean = re.sub(r"/\*.*?\*/", "", clean, flags=re.DOTALL)  # block comments
    clean = clean.strip()

    # Must begin with SELECT after comment removal.
    if not clean.upper().startswith("SELECT"):
        raise ValueError("Only SELECT queries are allowed.")

    # No write/DDL/execution keywords anywhere in the query.
    match = _WRITE_KEYWORDS.search(clean)
    if match:
        raise ValueError(f"Query contains forbidden keyword '{match.group().upper()}'. Only read-only SELECT queries are permitted.")

    # SELECT INTO writes data to a new table.
    if _SELECT_INTO.search(clean):
        raise ValueError("SELECT INTO is not allowed.")

    # Multiple statements allow a SELECT to smuggle in a second write statement.
    # A trailing semicolon is fine; a semicolon followed by more content is not.
    if re.search(r";.+\S", clean):
        raise ValueError("Multiple statements are not allowed.")


async def get_data(query: str) -> list[dict]:
    '''This function uses the query from the agent to retrieve data from the database.

    Args:
        - query (str): The SQL query to be executed on the database.
    Returns:
        - result (list): The result of the SQL query execution.
    '''
    try:
        _assert_read_only(query)
    except ValueError as e:
        return {"error": str(e)}

    try:
        async with _SessionFactory() as session:
            result = await session.execute(text(query))
            rows = result.mappings().all()
            return [
                {
                    k: str(v) if not isinstance(v, (str, int, float, bool, type(None))) else v
                    for k, v in row.items()
                }
                for row in rows
            ]
    except Exception as e:
        return {"error": str(e)}

# # ── Tool 2: Create routine ────────────────────────────────────────────────────

# def create_routine(
#     user_id: int,
#     name: str,
#     exercises: list[dict],
#     description: str = "",
# ) -> str:
#     """
#     Create and save a new routine for the user using only exercises that already
#     exist in the GymBro exercise library. Invalid exercise IDs are rejected before
#     anything is written.

#     IMPORTANT: Before calling this tool you MUST call get_data to look up real
#     exercise IDs from the exercises table. Never guess or invent UUIDs.

#     Args:
#         user_id:     The Telegram user ID to assign the routine to.
#         name:        Name of the routine (e.g. "Push Day A").
#         exercises:   List of exercises to include. Each item is a dict with:
#                        - exercise_id    (str, UUID) — must exist in exercises table
#                        - planned_sets   (int)        — number of sets
#                        - planned_reps   (int)        — target reps per set
#                        - planned_weight (float|None) — target weight in kg, None for bodyweight
#         description: Optional description of the routine.

#     Returns:
#         Success message listing what was saved, or a detailed error message.
#     """
#     if not exercises:
#         return "ERROR: At least one exercise is required."

#     # ── Validate exercise_id format ───────────────────────────────────────────
#     requested_ids = []
#     for ex in exercises:
#         try:
#             requested_ids.append(str(uuid.UUID(str(ex["exercise_id"]))))
#         except (ValueError, KeyError):
#             return f"ERROR: Invalid exercise_id format: {ex.get('exercise_id')}. Use get_data to find valid IDs."

#     conn = _connect()
#     try:
#         cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

#         # ── Validate all exercise IDs exist in the library ────────────────────
#         cur.execute(
#             "SELECT id, name FROM exercises WHERE id = ANY(%s::uuid[])",
#             (requested_ids,),
#         )
#         found = {str(row["id"]): row["name"] for row in cur.fetchall()}
#         missing = [eid for eid in requested_ids if eid not in found]

#         if missing:
#             return (
#                 f"ERROR: These exercise IDs do not exist in the library: {missing}. "
#                 f"Use get_data to search the exercises table and get valid IDs."
#             )

#         # ── Insert routine ────────────────────────────────────────────────────
#         routine_id = str(uuid.uuid4())
#         cur.execute(
#             """
#             INSERT INTO routines (id, user_id, name, description)
#             VALUES (%s, %s, %s, %s)
#             """,
#             (routine_id, user_id, name.strip(), description.strip() or None),
#         )

#         # ── Insert routine_exercises in order ─────────────────────────────────
#         for order, ex in enumerate(exercises, start=1):
#             planned_weight = ex.get("planned_weight")
#             cur.execute(
#                 """
#                 INSERT INTO routine_exercises
#                     (id, routine_id, exercise_id, "order", planned_sets, planned_reps, planned_weight)
#                 VALUES (%s, %s, %s, %s, %s, %s, %s)
#                 """,
#                 (
#                     str(uuid.uuid4()),
#                     routine_id,
#                     ex["exercise_id"],
#                     order,
#                     int(ex["planned_sets"]),
#                     int(ex["planned_reps"]),
#                     float(planned_weight) if planned_weight is not None else None,
#                 ),
#             )

#         conn.commit()

#         # ── Confirmation summary ──────────────────────────────────────────────
#         lines = [f"Routine '{name}' saved successfully (ID: {routine_id}).","Exercises:"]
#         for i, (eid, ex) in enumerate(zip(requested_ids, exercises)):
#             weight_str = f" @ {ex.get('planned_weight')}kg" if ex.get("planned_weight") else " (bodyweight)"
#             lines.append(f"  {i+1}. {found[eid]} — {ex['planned_sets']}×{ex['planned_reps']}{weight_str}")

#         return "\n".join(lines)

#     except Exception as e:
#         conn.rollback()
#         return f"ERROR creating routine: {e}"
#     finally:
#         conn.close()
